server:
  #服务器的HTTP端口
  port: 8080

# 前后端不分离，所以下面不用
#ThymeleafAutoConfiguration 类通过 @EnableConfigurationProperties 注入 ThymeleafProperties.class
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
